site_name: bydantic
site_url: https://kylehusmann.com/bydantic
repo_url: https://github.com/khusmann/bydantic

nav:
  - Welcome to bydantic: index.md
  - Getting Started: getting-started.md
  - More Field Types: more-field-types.md
  - Complex Data Structures: complex-data-structures.md
  - Advanced Features: advanced-features.md
  - Field Type Reference: field-type-reference.md
  - Bitfield Class Reference: bitfield-class-reference.md

theme:
  name: material
  custom_dir: overrides
  features:
    - content.code.copy

extra:
  analytics:
    provider: goatcounter
    code: bydantic

watch:
  - src

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
      - name: mermaid
        class: mermaid
        format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            separate_signature: true
            show_signature_annotations: true
            show_overloads: false
            annotations_path: brief
            docstring_style: google
            show_root_heading: true
            show_root_full_path: false
            show_source: false
  - gen-files:
      scripts:
        - update_readme.py