site_name: bydantic
site_url: https://kylehusmann.com/bydantic
repo_url: https://github.com/khusmann/bydantic

nav:
  - Welcome to bydantic: index.md
  - Getting Started: getting-started.md
  - Serialization & Deserialization Context: serialization-deserialization-context.md
  - Bitfield Reordering / Alignment: bitfield-reordering-alignment.md
  - Field Type Reference: field-type-reference.md
  - Bitfield Class Reference: bitfield-class-reference.md

theme:
  name: material
  features:
    - content.code.copy

watch:
  - src

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            separate_signature: true
            show_signature_annotations: true
            show_overloads: false
            annotations_path: brief
            docstring_style: google
            show_root_heading: true
            show_root_full_path: false
            show_source: false
  - gen-files:
      scripts:
        - update_readme.py